include:
  # Serviços
  # - ./GitLab/docker-compose.yml
  - ./Nextcloud/docker-compose.yml
  - ./OpenWebUI/docker-compose.yml
  - ./FreshRSS/docker-compose.yml
  - ./Searxng/docker-compose.yml

  # HTTP
  - ./ProxyHttp/docker-compose.yml

  # DNS
  - ./CoreDNS/docker-compose.yml
  - ./Unbound/docker-compose.yml
  - ./Pi-Hole/docker-compose.yml

  # Gerenciamento
  - ./Dockpeek/docker-compose.yml
  - ./Portainer/docker-compose.yml

networks:
  dns-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.254.0.0/24
  default: