services:
  powerdns_admin:
    image: powerdnsadmin/pda-legacy:latest
    container_name: powerdns_admin
    hostname: powerdns_admin
    depends_on:
      powerdns_auth:
        condition: service_healthy
    environment:
      - SQLALCHEMY_DATABASE_URI=mysql://${POWERDNS_DB_USER}:${POWERDNS_DB_PASS}@powerdns_db/${POWERDNS_DB_NAME}
      - PDNS_API_URL=http://powerdns_auth:8181/
      - PDNS_API_KEY=${POWERDNS_API_KEY}
    volumes:
      - powerdns_db_admin_upload:/app/upload
    ports:
      - "9191:80"
    networks:
      powerdns_network:
      default:
  powerdns_auth:
    image: powerdns/pdns-auth-50:latest
    container_name: powerdns_auth
    hostname: powerdns_auth
    depends_on:
      powerdns_db:
        condition: service_healthy
    environment:
      - PDNS_LOCAL_ADDRESS="0.0.0.0,::"
      - PDNS_LAUNCH=gmysql
      - PDNS_GMYSQL_HOST=powerdns_db
      - PDNS_GMYSQL_PORT=3306
      - PDNS_GMYSQL_DBNAME=powerdns
      - PDNS_GMYSQL_USER=powerdns
      - PDNS_GMYSQL_PASSWORD=${POWERDNS_DB_PASS}
      - PDNS_API=yes
      - PDNS_API_KEY=${POWERDNS_API_KEY}
      - PDNS_WEBSERVER=yes
      - PDNS_WEBSERVER_ADDRESS=0.0.0.0
      - PDNS_WEBSERVER_PORT=8081
      - PDNS_WEBSERVER_ALLOW_FROM=0.0.0.0/0
      - PDNS_DEFAULT_TTL=3600
      - PDNS_DISABLE_SYSLOG=yes
      - PDNS_LOGLEVEL=4
    ports:
      - "55:53/tcp"
      - "53:53/udp"
    networks:
      powerdns_network:
      dns-network:
        ipv4_address: 172.254.0.252
      default:
    healthcheck:
      test: ["CMD", "pdns_control", "rping"]
      interval: 15s
      timeout: 5s
      retries: 5
  powerdns_db:
    image: mariadb:11
    restart: unless-stopped
    container_name: powerdns_db
    hostname: powerdns_db
    environment:
      MARIADB_ROOT_PASSWORD: "${POWERDNS_DB_ROOT_PASS}"
      MARIADB_DATABASE: "${POWERDNS_DB_NAME}"
      MARIADB_USER: "${POWERDNS_DB_USER}"
      MARIADB_PASSWORD: "${POWERDNS_DB_PASS}"
    volumes:
      - powerdns_db:/var/lib/mysql
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro
    networks:
      powerdns_network:
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 10
    
volumes:
  powerdns_db:
  powerdns_db_admin_upload:

networks:
  powerdns_network: