apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: minio-tenant

resources:
- namespace.yaml
- tenant-config.yaml
- storage-user.yaml
- tenant.yaml
- minio-pv0.yaml
- minio-pv1.yaml
- minio-pv2.yaml
- minio-pv3.yaml
- minio-pv4.yaml
- minio-storageclass.yaml
- console-nodeport.yaml