apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-pv-0
spec:
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteOnce
  storageClassName: minio-local
  hostPath:
    path: /var/minio